### ISSUE TITLE
Add feature to view assembly instructions in the values pane in the IDE

### ISSUE THREAD

**Issue by vazirim** [nativejdb/nativejdb#53]
- Obtain assembly instructions from GDB corresponding to a stack frame
- Populate a variable called "instructions" with a String value that contains a snippet of instructions

**Comment by jchen10500** [comment]
Progress so far: 

- Created a new variable called `$asm` in the variables pane 
![asm2](https://user-images.githubusercontent.com/75508867/178339801-9bcdfa04-be25-441d-8173-66791be7b51e.jpg)

- Retrieved assembly instructions at the current `$pc` using the gdb command `-data-disassemble`. The exact number of lines of instructions to retrieve can be modified (for later investigation)

GDB output: `10^done,asm_insns=[{address="0x0000555555add183",func-name="HelloNested.HelloNested::main(java.lang.String[] *)",offset="19",inst="mov    0x392ebe(%rip),%rax        # 0x555555e70048"}]` where the `inst` field gives the assembly instruction of the desired line number 


To do: 
- Send JDWP value information for non-primitive variables. JDWP requires an `objectID` that uniquely identifies an object in the target VM, which means the variable has to exist in the target VM. This means we cannot create an object in the VM and can pose an issue when replacing scaffolding VM

Files modified: 
- [JDWPMethod](https://github.com/jchen10500/nativejdb/blob/dev/src/main/java/jdwp/JDWPMethod.java#L199): add a new slot for assembly variable 
- [JDWPStackFrame](https://github.com/jchen10500/nativejdb/blob/dev/src/main/java/jdwp/JDWPStackFrame.java#L84): obtain assembly code from GDB

**Comment by jchen10500** [comment]
This feature has been tested with Quarkus applications. 
<img width="561" alt="08-13-22 test asm with quarkus" src="https://user-images.githubusercontent.com/75508867/184668590-fef07c8d-286e-4c19-a076-b117d93ad5af.png">
